# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Loop-Wx
version:      0.04
version_from: lib/POE/Loop/Wx.pm
installdirs:  site
requires:
    POE:                           0.3009
    Test::More:                    0
    Wx:                            0.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
